"use client";

import "~/styles/globals.css";

import { useEffect, useState } from "react";
import { Geist } from "next/font/google";

import SideNav from "~/components/nav/SideNav";
import { TRPCReactProvider } from "~/trpc/react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [wallpaper, setWallpaper] = useState("");
  const availableWallpapers = [
    "/daniel-shapiro-K3NwBdSaja0-unsplash.jpg",
    "/dominik-schroder-FIKD9t5_5zQ-unsplash.jpg",
    "/paul-pastourmatzis-KT3WlrL_bsg-unsplash.jpg",
  ];
  useEffect(() => {
    const randomWallpaper =
      availableWallpapers[
        Math.floor(Math.random() * availableWallpapers.length)
      ];
    if (randomWallpaper) {
      setWallpaper(randomWallpaper);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <div
            className={`flex h-screen overflow-hidden bg-cover bg-fixed bg-center`}
            style={{
              backgroundImage: `url('${wallpaper}')`,
            }}
          >
            <SideNav />
            <main className="flex grow overflow-hidden">{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
